<section class="mt-3 card card-body">
    <h1>NOVO USUARIO</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="name" type="text" id="name" class="form-control mb-3">
                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-3">
                <label for="senha">Senha</label>
                <input name="password" type="text" id="password" class="form-control mb-3">
                <label for="profile">Perfil</label>
                <input name="profile" type="text" id="profile" class="form-control mb-3">
                <select name="profile" id="profile"></select>
                <option >Normal</option>
                
                
                <button class="btn btn-primary">Pronto</button>
               
            </form>

        </div>
    </div>
</section>