<section class="mt-3 card card-body">
    <h1>EDITAR ALUNO</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-contrl mb-3">
                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-contrl mb-3">
                <label for="cpf">CPF</label>
                <input name="cpf" type="text" id="cpf" class="form-contrl mb-3">
                <label for="nascimento">Data de Nascimento</label>
                <input name="nascimento" type="text" id="nascimento" class="form-contrl mb-3">
                <label for="genero">Genero</label>
                <input name="genero" type="text" id="genero" class="form-contrl mb-3">
                
                <button class="btn btn-primary">Pronto</button>
               
            </form>

        </div>
    </div>
</section>