<section class="mt-3 card card-body">
    <h1>
        PROFESSORES
    </h1>

    <div>
        <a href="/alunos/novo" class="btn btn-outline-dark">DADOS DO PROFESSOR</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Matrícula</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Ações</th>
            </tr>
        </thead>

    </table>

</section>