<nav class="mt-3 d-flex justify-content-between">
    <div class="text-start">
    <a href='/' class="btn btn-outline-dark">INICIO</a>
    <a href='/alunos/listar' class="btn btn-outline-dark">ALUNO</a>
    <a href='/professores/listar' class="btn btn-outline-dark">PREFESSOR</a>
    <a href='/cursos/listar' class="btn btn-outline-dark">CURSO</a>
    

    </div>
    <a href='/logout' class="btn btn-outline-dark">DESCONECTAR</a>
    <div>

    </div>
   
</nav>

